# Generated by Django 4.2.6 on 2023-10-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_indexpage_homegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homegalleryimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
