# Generated by Django 4.2.6 on 2023-11-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote_request', '0002_formfield_formpage_delete_quoterequest_and_more'),
        ('home', '0005_rootredirectpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='form_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quote_request.formpage'),
        ),
    ]
