# Generated by Django 4.2.6 on 2023-11-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_indexpage_form_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpage',
            name='form_page',
        ),
    ]
