# Generated by Django 4.2.6 on 2023-11-20 19:27

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_indexpage_form_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='featured',
            field=wagtail.fields.StreamField([('about', wagtail.blocks.PageChooserBlock(required=False)), ('services', wagtail.blocks.PageChooserBlock(required=False)), ('posts', wagtail.blocks.PageChooserBlock(required=False))], default=None, use_json_field=True),
            preserve_default=False,
        ),
    ]
