# Generated by Django 4.2.6 on 2023-11-26 09:31

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_indexpage_form_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='featured',
            field=wagtail.fields.StreamField([('home1', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=45)), ('intro', wagtail.blocks.RichTextBlock(help_text='Do not use more than 200 characters!', max_length=200)), ('focus1_header', wagtail.blocks.RichTextBlock(help_text='Do not use more than 25 characters!', max_length=25)), ('image1', wagtail.images.blocks.ImageChooserBlock()), ('focus1_text', wagtail.blocks.RichTextBlock(help_text='Do not use more than 120 characters!', max_length=120)), ('focus2_header', wagtail.blocks.RichTextBlock(help_text='Do not use more than 120 characters!', max_length=120)), ('image2', wagtail.images.blocks.ImageChooserBlock()), ('focus2_text', wagtail.blocks.RichTextBlock(help_text='Do not use more than 120 characters!', max_length=120))])), ('home2', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=21)), ('text', wagtail.blocks.RichTextBlock(help_text='Do not use more than 120 characters!', max_length=120))])), ('home3', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=30)), ('focus1_header', wagtail.blocks.CharBlock(max_length=25)), ('image1', wagtail.images.blocks.ImageChooserBlock()), ('focus1_text', wagtail.blocks.CharBlock(max_length=120)), ('focus2_header', wagtail.blocks.CharBlock(max_length=25)), ('image2', wagtail.images.blocks.ImageChooserBlock()), ('focus2_text', wagtail.blocks.CharBlock(max_length=120)), ('special_text', wagtail.blocks.CharBlock(max_length=45))])), ('home4', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=60)), ('intro', wagtail.blocks.CharBlock(max_length=120)), ('image1', wagtail.images.blocks.ImageChooserBlock()), ('sub_header1', wagtail.blocks.CharBlock(max_length=13)), ('text1', wagtail.blocks.CharBlock(max_length=51)), ('image2', wagtail.images.blocks.ImageChooserBlock()), ('sub_header2', wagtail.blocks.CharBlock(max_length=13)), ('text2', wagtail.blocks.CharBlock(max_length=51)), ('image3', wagtail.images.blocks.ImageChooserBlock()), ('sub_header3', wagtail.blocks.CharBlock(max_length=13)), ('text3', wagtail.blocks.CharBlock(max_length=51)), ('cover_image', wagtail.images.blocks.ImageChooserBlock())])), ('home5', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=30)), ('intro', wagtail.blocks.RichTextBlock(help_text='two lines, each with atmost 58 characters', max_length=120)), ('sub_header1', wagtail.blocks.CharBlock(max_length=15)), ('text1', wagtail.blocks.CharBlock(max_length=120)), ('image1', wagtail.images.blocks.ImageChooserBlock()), ('sub_header2', wagtail.blocks.CharBlock(max_length=15)), ('text2', wagtail.blocks.CharBlock(max_length=120)), ('image2', wagtail.images.blocks.ImageChooserBlock()), ('sub_header3', wagtail.blocks.CharBlock(max_length=15)), ('text3', wagtail.blocks.CharBlock(max_length=120)), ('image3', wagtail.images.blocks.ImageChooserBlock())])), ('form_ext', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=30)), ('intro', wagtail.blocks.CharBlock(max_length=120)), ('heading1', wagtail.blocks.CharBlock(max_length=15)), ('text1', wagtail.blocks.RichTextBlock(max_length=100)), ('heading2', wagtail.blocks.CharBlock(max_length=15)), ('email', wagtail.blocks.EmailBlock()), ('call', wagtail.blocks.IntegerBlock()), ('feed_back', wagtail.blocks.CharBlock()), ('mobile', wagtail.blocks.IntegerBlock())]))], default=None, use_json_field=True),
            preserve_default=False,
        ),
    ]
