# Generated by Django 4.2.6 on 2023-11-26 18:55

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_indexpage_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='featured',
            field=wagtail.fields.StreamField([('services', wagtail.blocks.PageChooserBlock(required=False)), ('posts', wagtail.blocks.PageChooserBlock(required=False))], use_json_field=True),
        ),
    ]
