# Generated by Django 4.2.6 on 2023-11-27 20:20

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_indexpage_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='featured',
            field=wagtail.fields.StreamField([('services', wagtail.blocks.PageChooserBlock(required=False)), ('posts', wagtail.blocks.PageChooserBlock(required=False)), ('carousel', wagtail.blocks.StructBlock([('heading1', wagtail.blocks.TextBlock()), ('text1', wagtail.blocks.TextBlock()), ('heading2', wagtail.blocks.TextBlock()), ('text2', wagtail.blocks.TextBlock()), ('heading3', wagtail.blocks.TextBlock()), ('text3', wagtail.blocks.TextBlock())])), ('carousel1', wagtail.blocks.StructBlock([('heading', wagtail.blocks.TextBlock()), ('intro', wagtail.blocks.TextBlock())])), ('carousel2', wagtail.blocks.StructBlock([('heading', wagtail.blocks.TextBlock()), ('intro', wagtail.blocks.TextBlock())])), ('carousel3', wagtail.blocks.StructBlock([('heading', wagtail.blocks.TextBlock()), ('intro', wagtail.blocks.TextBlock())])), ('home1', wagtail.blocks.StructBlock([('heading', wagtail.blocks.TextBlock()), ('intro', wagtail.blocks.TextBlock()), ('image1', wagtail.images.blocks.ImageChooserBlock()), ('sub_header1', wagtail.blocks.TextBlock()), ('text1', wagtail.blocks.TextBlock()), ('image2', wagtail.images.blocks.ImageChooserBlock()), ('sub_header2', wagtail.blocks.TextBlock()), ('text2', wagtail.blocks.TextBlock())])), ('home2', wagtail.blocks.StructBlock([('heading', wagtail.blocks.TextBlock()), ('image1', wagtail.images.blocks.ImageChooserBlock()), ('sub_header1', wagtail.blocks.TextBlock()), ('text1', wagtail.blocks.TextBlock()), ('image2', wagtail.images.blocks.ImageChooserBlock()), ('sub_header2', wagtail.blocks.TextBlock()), ('text2', wagtail.blocks.TextBlock())])), ('home3', wagtail.blocks.StructBlock([('heading', wagtail.blocks.TextBlock()), ('intro', wagtail.blocks.TextBlock()), ('image1', wagtail.images.blocks.ImageChooserBlock()), ('sub_header1', wagtail.blocks.TextBlock()), ('text1', wagtail.blocks.TextBlock()), ('image2', wagtail.images.blocks.ImageChooserBlock()), ('sub_header2', wagtail.blocks.TextBlock()), ('text2', wagtail.blocks.TextBlock()), ('image3', wagtail.images.blocks.ImageChooserBlock()), ('sub_header3', wagtail.blocks.TextBlock()), ('text3', wagtail.blocks.TextBlock())])), ('home4', wagtail.blocks.StructBlock([('heading', wagtail.blocks.TextBlock()), ('intro', wagtail.blocks.TextBlock()), ('image1', wagtail.images.blocks.ImageChooserBlock()), ('sub_header1', wagtail.blocks.TextBlock()), ('text1', wagtail.blocks.TextBlock()), ('image2', wagtail.images.blocks.ImageChooserBlock()), ('sub_header2', wagtail.blocks.TextBlock()), ('text2', wagtail.blocks.TextBlock()), ('image3', wagtail.images.blocks.ImageChooserBlock()), ('sub_header3', wagtail.blocks.TextBlock()), ('text3', wagtail.blocks.TextBlock())]))], use_json_field=True),
        ),
    ]
