# Generated by Django 4.2.6 on 2023-12-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_indexpage_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='air_contact',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='mtn_contact',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
