# Generated by Django 4.2.6 on 2023-12-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_indexpage_air_contact_indexpage_mtn_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexpage',
            old_name='air_contact',
            new_name='airtel_contact',
        ),
    ]
