# Generated by Django 4.2.6 on 2023-11-22 19:52

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('about_block', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length='45')), ('intro', wagtail.blocks.CharBlock(max_length='250')), ('mini_para1', wagtail.blocks.CharBlock(max_length='120')), ('mini_para2', wagtail.blocks.CharBlock(max_length='120')), ('outro', wagtail.blocks.CharBlock(max_length='250'))])), ('about_director', wagtail.blocks.StructBlock([('heading1', wagtail.blocks.RichTextBlock()), ('message', wagtail.blocks.RichTextBlock())])), ('faqs', wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(max_length='50')), ('answer', wagtail.blocks.CharBlock(max_length='250'))])), ('goals', wagtail.blocks.StructBlock([('header', wagtail.blocks.RichTextBlock()), ('text', wagtail.blocks.RichTextBlock())]))], use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
