# Generated by Django 4.2.6 on 2023-11-23 14:07

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.StreamField([('about_block', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length='45')), ('intro', wagtail.blocks.CharBlock(max_length='250')), ('mini_para1', wagtail.blocks.CharBlock(max_length='120')), ('mini_para2', wagtail.blocks.CharBlock(max_length='120')), ('outro', wagtail.blocks.CharBlock(max_length='250'))])), ('about_director', wagtail.blocks.StructBlock([('heading1', wagtail.blocks.RichTextBlock()), ('message', wagtail.blocks.RichTextBlock())])), ('faqs', wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(max_length='50')), ('answer', wagtail.blocks.CharBlock(max_length='250'))])), ('goals', wagtail.blocks.StructBlock([('header', wagtail.blocks.RichTextBlock()), ('text', wagtail.blocks.RichTextBlock()), ('number', wagtail.blocks.IntegerBlock()), ('image1', wagtail.images.blocks.ImageChooserBlock())]))], use_json_field=True),
        ),
    ]
