# Generated by Django 4.2.6 on 2023-11-23 16:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.CharField(blank=True, max_length=250)),
                ('displayed', wagtail.fields.StreamField([('firsts', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=120)), ('text', wagtail.blocks.RichTextBlock())])), ('secs', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=120)), ('intro', wagtail.blocks.RichTextBlock()), ('text1', wagtail.blocks.CharBlock(max_length=30)), ('text2', wagtail.blocks.CharBlock(max_length=30)), ('text3', wagtail.blocks.CharBlock(max_length=30)), ('text4', wagtail.blocks.CharBlock(max_length=30)), ('text5', wagtail.blocks.CharBlock(max_length=30)), ('text6', wagtail.blocks.CharBlock(max_length=30)), ('outro', wagtail.blocks.RichTextBlock())]))], use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicePostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('body_class', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=30)), ('core_intro', wagtail.blocks.CharBlock(max_length=120)), ('intro', wagtail.blocks.RichTextBlock()), ('image1', wagtail.images.blocks.ImageChooserBlock()), ('paragraph1', wagtail.blocks.RichTextBlock()), ('paragraph2', wagtail.blocks.RichTextBlock()), ('thought1', wagtail.blocks.RichTextBlock()), ('thought2', wagtail.blocks.RichTextBlock()), ('paragraphs', wagtail.blocks.RichTextBlock())]))], use_json_field=True)),
                ('header_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
