# Generated by Django 4.2.6 on 2023-11-24 07:12

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_servicepostpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblogpage',
            name='description',
            field=wagtail.fields.RichTextField(help_text='Each sentence should have a max of 20 char', max_length=60),
        ),
        migrations.AlterField(
            model_name='servicepostpage',
            name='body',
            field=wagtail.fields.StreamField([('body_class', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=30)), ('core_intro', wagtail.blocks.CharBlock(max_length=120)), ('intro', wagtail.blocks.RichTextBlock()), ('image1', wagtail.images.blocks.ImageChooserBlock()), ('paragraph1', wagtail.blocks.RichTextBlock()), ('paragraph2', wagtail.blocks.RichTextBlock()), ('thought1', wagtail.blocks.RichTextBlock()), ('thought2', wagtail.blocks.RichTextBlock()), ('paragraphs', wagtail.blocks.RichTextBlock()), ('post_number', wagtail.blocks.IntegerBlock())]))], use_json_field=True),
        ),
    ]
