# Generated by Django 4.2.6 on 2023-11-24 08:02

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_serviceblogpage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblogpage',
            name='displayed',
            field=wagtail.fields.StreamField([('firsts', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=120)), ('text', wagtail.blocks.RichTextBlock())])), ('secs', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=120)), ('intro', wagtail.blocks.RichTextBlock()), ('text1', wagtail.blocks.RichTextBlock(max_length=30)), ('text2', wagtail.blocks.RichTextBlock(max_length=30)), ('text3', wagtail.blocks.RichTextBlock(max_length=30)), ('text4', wagtail.blocks.RichTextBlock(max_length=30)), ('text5', wagtail.blocks.RichTextBlock(max_length=30)), ('text6', wagtail.blocks.RichTextBlock(max_length=30)), ('outro', wagtail.blocks.RichTextBlock())]))], use_json_field=True),
        ),
    ]
