# Generated by Django 4.2.6 on 2023-11-24 08:08

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_serviceblogpage_displayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblogpage',
            name='displayed',
            field=wagtail.fields.StreamField([('firsts', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=120)), ('text', wagtail.blocks.RichTextBlock())])), ('secs', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=120)), ('intro', wagtail.blocks.RichTextBlock()), ('text1', wagtail.blocks.RichTextBlock()), ('outro', wagtail.blocks.RichTextBlock())]))], use_json_field=True),
        ),
    ]
