# Generated by Django 4.2.6 on 2023-11-24 08:49

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_serviceblogpage_displayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblogpage',
            name='description',
            field=wagtail.fields.RichTextField(help_text='Each sentence should have a max of 19 characters', max_length=60),
        ),
    ]
