# Generated by Django 4.2.6 on 2023-11-24 09:10

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_serviceblogpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblogpage',
            name='displayed',
            field=wagtail.fields.StreamField([('firsts', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=120)), ('text', wagtail.blocks.RichTextBlock()), ('image1', wagtail.images.blocks.ImageChooserBlock())])), ('secs', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=120)), ('intro', wagtail.blocks.RichTextBlock()), ('text1', wagtail.blocks.CharBlock(max_length=30)), ('text2', wagtail.blocks.CharBlock(max_length=30)), ('text3', wagtail.blocks.CharBlock(max_length=30)), ('text4', wagtail.blocks.CharBlock(max_length=30)), ('text5', wagtail.blocks.CharBlock(max_length=30)), ('text6', wagtail.blocks.CharBlock(max_length=30)), ('outro', wagtail.blocks.RichTextBlock()), ('image1', wagtail.images.blocks.ImageChooserBlock())]))], use_json_field=True),
        ),
    ]
