# Generated by Django 4.2.6 on 2023-11-29 13:45

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_serviceblogpage_displayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepostpage',
            name='body',
            field=wagtail.fields.StreamField([('body_class', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=30)), ('intro', wagtail.blocks.RichTextBlock()), ('image1', wagtail.images.blocks.ImageChooserBlock()), ('paragraph1', wagtail.blocks.RichTextBlock()), ('paragraph2', wagtail.blocks.TextBlock()), ('thought1', wagtail.blocks.RichTextBlock()), ('thought2', wagtail.blocks.RichTextBlock()), ('paragraphs', wagtail.blocks.RichTextBlock()), ('post_number', wagtail.blocks.IntegerBlock())]))], use_json_field=True),
        ),
    ]
