# Generated by Django 4.2.6 on 2023-12-05 20:17

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_servicepostpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblogpage',
            name='displayed',
            field=wagtail.fields.StreamField([('firsts', wagtail.blocks.StructBlock([('heading', wagtail.blocks.TextBlock(max_length=120)), ('text', wagtail.blocks.TextBlock()), ('image1', wagtail.images.blocks.ImageChooserBlock())])), ('secs', wagtail.blocks.StructBlock([('heading', wagtail.blocks.TextBlock(max_length=120)), ('intro', wagtail.blocks.TextBlock()), ('text1', wagtail.blocks.TextBlock(max_length=30)), ('text2', wagtail.blocks.TextBlock(max_length=30)), ('text3', wagtail.blocks.TextBlock(max_length=30)), ('text4', wagtail.blocks.TextBlock(max_length=30)), ('text5', wagtail.blocks.TextBlock(max_length=30)), ('text6', wagtail.blocks.TextBlock(max_length=30)), ('outro', wagtail.blocks.TextBlock()), ('image1', wagtail.images.blocks.ImageChooserBlock())]))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='servicepostpage',
            name='body',
            field=wagtail.fields.StreamField([('body_class', wagtail.blocks.StructBlock([('heading', wagtail.blocks.TextBlock(max_length=30)), ('intro', wagtail.blocks.TextBlock()), ('image1', wagtail.images.blocks.ImageChooserBlock()), ('paragraph1', wagtail.blocks.TextBlock()), ('paragraph2', wagtail.blocks.TextBlock()), ('thought1', wagtail.blocks.RichTextBlock()), ('thought2', wagtail.blocks.RichTextBlock()), ('paragraphs', wagtail.blocks.TextBlock()), ('post_number', wagtail.blocks.IntegerBlock())]))], use_json_field=True),
        ),
    ]
