# Generated by Django 4.2.6 on 2023-12-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_serviceblogpage_displayed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceblogpage',
            name='contact',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
