# Generated by Django 4.2.6 on 2023-11-10 18:39

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_postpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='quote',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(max_length=450),
        ),
    ]
