# Generated by Django 4.2.6 on 2023-11-13 10:00

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('garage', '0005_postpage_postpageblogcategory_postpagetags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taggit.tag',),
        ),
        migrations.AddField(
            model_name='postpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('published_at', wagtail.blocks.DateBlock(required='True')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], default=None, use_json_field=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BlogGalleryImage',
        ),
    ]
