# Generated by Django 4.2.6 on 2023-11-14 08:59

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0007_alter_postpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('published_at', wagtail.blocks.DateBlock(required='True')), ('paragraph_with_image', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('paragraph', wagtail.blocks.RichTextBlock())], use_json_field=True),
        ),
    ]
