# Generated by Django 4.2.6 on 2023-11-14 15:56

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0009_alter_postpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('published_at', wagtail.blocks.DateBlock(required='True')), ('paragraph1', wagtail.blocks.RichTextBlock()), ('image1', wagtail.images.blocks.ImageChooserBlock()), ('quotation', wagtail.blocks.RichTextBlock()), ('mini_para', wagtail.blocks.RichTextBlock()), ('image2', wagtail.images.blocks.ImageChooserBlock()), ('paragraphs', wagtail.blocks.RichTextBlock())], use_json_field=True),
        ),
    ]
