# Generated by Django 4.2.6 on 2023-12-05 19:56

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0013_alter_postpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('special_intro', wagtail.blocks.CharBlock(max_length=200)), ('published_at', wagtail.blocks.DateBlock(required='True')), ('paragraph1', wagtail.blocks.RichTextBlock()), ('image1', wagtail.images.blocks.ImageChooserBlock()), ('quotation', wagtail.blocks.RichTextBlock()), ('mini_para', wagtail.blocks.RichTextBlock()), ('paragraphs', wagtail.blocks.RichTextBlock()), ('caption_display_text', wagtail.blocks.TextBlock(max_length='83'))], use_json_field=True),
        ),
    ]
